#ifdef OPT_MATERIALX

// Generated by validate-mtlx and injected in pathtrace.glsl.
vec3 EvalMtlxClosure(int matID, State state, vec3 V, vec3 N, vec3 L, out float pdf, out int flags);
vec3 SampleMtlxClosure(int matID, State state, vec3 V, vec3 N, out vec3 L, out float pdf, out int flags);

int ClosureFlagsFromDirection(vec3 V, vec3 L)
{
    return (dot(V, L) >= 0.0) ? CLOSURE_FLAG_REFLECT : CLOSURE_FLAG_TRANSMIT;
}

#endif

bool ClosureSupportsDirection(int flags, vec3 V, vec3 L)
{
#ifdef OPT_MATERIALX
    int requested = ClosureFlagsFromDirection(V, L);
    return (flags & requested) != 0;
#else
    return true;
#endif
}

vec3 EvalClosureBridge(State state, vec3 V, vec3 N, vec3 L, out float pdf, out int flags)
{
#if defined(OPT_MATERIALX) && !defined(OPT_PREVIEW)
    // Per-material runtime dispatch: MaterialX materials use the generated
    // closure; every other type (Disney, or an unknown/unsupported type) falls
    // back to the built-in Disney model (deterministic fallback, FR-010).
    // In preview mode (OPT_PREVIEW) the heavy MaterialX closure is skipped and
    // all materials are shaded with the cheap built-in Disney model for speed.
    if (state.mat.materialType == MATERIAL_TYPE_MATERIALX)
        return EvalMtlxClosure(state.matID, state, V, N, L, pdf, flags);
    flags = 0;
    return DisneyEval(state, V, N, L, pdf);
#else
    flags = 0;
    return DisneyEval(state, V, N, L, pdf);
#endif
}

vec3 SampleClosureBridge(State state, vec3 V, vec3 N, out vec3 L, out float pdf, out int flags)
{
#if defined(OPT_MATERIALX) && !defined(OPT_PREVIEW)
    if (state.mat.materialType == MATERIAL_TYPE_MATERIALX)
        return SampleMtlxClosure(state.matID, state, V, N, L, pdf, flags);
    flags = 0;
    return DisneySample(state, V, N, L, pdf);
#else
    flags = 0;
    return DisneySample(state, V, N, L, pdf);
#endif
}
